services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: "ticketsystem"
      MYSQL_ROOT_PASSWORD: "fpt_itsm"
    ports:
      - 3306:3306
    restart: always
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql: