server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/ticketsystem"
    username: root
    password: fpt_itsm
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
jwt:
  signerKey: "wW4pYfEUZNCa3FcB7LMqQ4PtBQEBNaTlSK03edB12Cs3/fwJ64JNGFPvlkj6+UbI"
